services:
      
  tienda-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - tienda_network

networks:
  tienda_network:
    driver: bridge
